package com.example.paktrainfoodapp.utils;

import android.content.Context;
import android.content.Intent;

import androidx.annotation.Nullable;

import com.google.android.gms.auth.api.signin.GoogleSignIn;
import com.google.android.gms.auth.api.signin.GoogleSignInAccount;
import com.google.android.gms.auth.api.signin.GoogleSignInClient;
import com.google.android.gms.auth.api.signin.GoogleSignInOptions;
import com.google.android.gms.common.api.ApiException;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.AuthCredential;
import com.google.firebase.auth.GoogleAuthProvider;

/**
 * Wraps Google Sign-In so all three roles (passenger / restaurant / delivery)
 * share one implementation.
 *
 * The web client id is looked up by name at runtime instead of via
 * R.string.default_web_client_id. That resource is generated by the
 * google-services plugin only once Google sign-in has been enabled in the
 * Firebase console; referencing it directly would stop the project compiling
 * until then. This way the app always builds, and Google login starts working
 * the moment a refreshed google-services.json is dropped in.
 */
public class GoogleSignInHelper {

    /** True once Google sign-in has been enabled in the Firebase console. */
    public static boolean isConfigured(Context context) {
        return webClientId(context) != null;
    }

    @Nullable
    public static String webClientId(Context context) {

        int resId = context.getResources().getIdentifier(
                "default_web_client_id", "string", context.getPackageName());

        if (resId == 0) return null;

        String value = context.getString(resId);

        return (value == null || value.trim().isEmpty()) ? null : value;
    }

    public static GoogleSignInClient buildClient(Context context) {

        String clientId = webClientId(context);

        GoogleSignInOptions.Builder builder =
                new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                        .requestEmail();

        if (clientId != null) {
            builder.requestIdToken(clientId);
        }

        return GoogleSignIn.getClient(context, builder.build());
    }

    /**
     * Turns the intent returned by the account picker into a Firebase
     * credential.
     *
     * @throws ApiException if the user cancelled or Play services failed
     */
    public static AuthCredential credentialFrom(Intent data) throws ApiException {

        Task<GoogleSignInAccount> task =
                GoogleSignIn.getSignedInAccountFromIntent(data);

        GoogleSignInAccount account = task.getResult(ApiException.class);

        return GoogleAuthProvider.getCredential(account.getIdToken(), null);
    }

    /** Signs out of Google too, so the next login shows the account picker. */
    public static void signOut(Context context) {
        buildClient(context).signOut();
    }
}
